# Generated by Django 4.0 on 2024-03-19 03:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('brand', models.CharField(default=0, max_length=100, verbose_name='Marca')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[inventario.models.validate_not_zero, django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('garantia', models.CharField(choices=[('1', '1 mes'), ('3', '3 meses'), ('6', '6 meses'), ('12', '1 año')], default='0', max_length=2, verbose_name='Garantía')),
                ('image', models.ImageField(upload_to='producto', verbose_name='Imagen_producto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El número de contacto debe tener 10 dígitos numéricos', regex='^[0-9]{10}$')], verbose_name='Número de celular')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[inventario.models.validate_not_zero], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[inventario.models.validate_not_zero, django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio total')),
                ('purchase_date', models.DateField(validators=[inventario.models.validate_not_future_date, inventario.models.validate_not_past_date], verbose_name='Fecha de compra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product', verbose_name='Nombre producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
                'ordering': ['id'],
            },
        ),
    ]
