# Generated by Django 4.0 on 2024-03-19 03:39

import django.core.validators
from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[inventario.models.validate_not_zero, django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
