# Generated by Django 4.0 on 2024-03-19 03:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ventas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garantias', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(validators=[ventas.models.validate_cantidad_no_cero], verbose_name='Cantidad vendida')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio total')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo')], default='Efectivo', max_length=30, verbose_name='Método de pago')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, validators=[ventas.models.validate_fecha_venta, ventas.models.validate_not_past_date], verbose_name='Fecha de venta')),
                ('client_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Ingrese un nombre válido (solo letras y espacios).', regex='^[a-zA-Z ]+$')], verbose_name='Nombre del cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('client_id', models.IntegerField(validators=[ventas.models.validate_client_id_length], verbose_name='Identificación del cliente')),
                ('garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garantias.garantiaproducto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product', verbose_name='Nombre producto')),
            ],
            options={
                'verbose_name': 'Venta de producto',
                'verbose_name_plural': 'Ventas de productos',
                'db_table': 'venta_producto',
                'ordering': ['id'],
            },
        ),
    ]
