# Generated by Django 5.0.2 on 2024-03-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_product',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo')], default='Efectivo', max_length=30, verbose_name='Método de pago'),
        ),
    ]
