# Generated by Django 5.0.2 on 2024-03-18 21:47

import django.db.models.deletion
import django.utils.timezone
import servicios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienteAtencion', '0001_initial'),
        ('garantias', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_requerido_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(validators=[servicios.models.validate_cantidad_no_cero], verbose_name='Cantidad del producto usada')),
                ('date', models.DateField(validators=[servicios.models.validate_not_future_date, servicios.models.validate_not_past_date], verbose_name='Fecha servicio del producto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product', verbose_name='Nombre producto')),
            ],
            options={
                'verbose_name': 'Producto requerido del servicio',
                'verbose_name_plural': 'Productos requeridos del servicio',
                'db_table': 'producto_requerido_servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=40, verbose_name='Nombre servicio')),
                ('client_name', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('client_id', models.CharField(max_length=12, verbose_name='Identificación del cliente')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca del vehiculo')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo del vehiculo')),
                ('year', models.PositiveIntegerField(verbose_name='Año del vehiculo')),
                ('color', models.CharField(max_length=50, verbose_name='Color del vehículo')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Número de placa')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Detalles del vehículo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio mano de obra')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio productos')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio total')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de venta')),
                ('time_date', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de venta')),
                ('state', models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='En proceso', max_length=20, verbose_name='Estado del servicio')),
                ('cite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clienteAtencion.cite', verbose_name='Cita')),
                ('garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garantias.garantia', verbose_name='servicio con garantía')),
                ('producto_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.producto_requerido_servicio', verbose_name='Productos usados')),
            ],
            options={
                'verbose_name': 'Venta de servicios',
                'verbose_name_plural': 'Ventas de servicios',
                'db_table': 'venta_servicio',
                'ordering': ['id'],
            },
        ),
    ]
