# Generated by Django 5.0.2 on 2024-03-18 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienteAtencion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienteAtencion.cite', verbose_name='Cita'),
        ),
    ]
