# Generated by Django 4.0 on 2024-03-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesiones', '0001_initial'),
        ('clienteAtencion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sesiones.customuser', verbose_name='Usuario'),
        ),
    ]
