# Generated by Django 4.0 on 2024-03-19 03:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import garantias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estados', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado de Garantía',
                'verbose_name_plural': 'Estados de Garantía',
                'db_table': 'EstadosGarantia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicioConGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[garantias.models.validate_not_zero, django.core.validators.MinValueValidator(0)], verbose_name='Precio mano de obra')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[garantias.models.validate_not_zero, django.core.validators.MinValueValidator(0)], verbose_name='Precio productos')),
                ('imagen', models.ImageField(upload_to='imagen', verbose_name='Imagen_servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RevisionGarantiaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision_garantia_servicio', models.DateField(validators=[garantias.models.validate_not_future_date, garantias.models.validate_not_past_date], verbose_name='Fecha revisión del servicio')),
                ('detalles_revision_garantia_servicio', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('cantidad_producto_servicio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de productos con garantía')),
                ('producto_garantia_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.product', verbose_name='Producto con garantía')),
            ],
            options={
                'verbose_name': 'Revision Garantía Servicio',
                'verbose_name_plural': 'Revision Garantía Servicio',
                'db_table': 'revision_garantia_servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RevisionGarantiaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision_garantia', models.DateField(validators=[garantias.models.validate_not_future_date, garantias.models.validate_not_past_date], verbose_name='Fecha revisión del producto')),
                ('detalles_revision_garantia', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad de productos con garantia')),
                ('producto_garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product', verbose_name='Producto con garantia')),
            ],
            options={
                'verbose_name': 'RevisionGarantiaProducto',
                'verbose_name_plural': 'Revision Garantia Producto',
                'db_table': 'RevisionGarantiaProducto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GarantiaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('codigo_garantia', models.PositiveIntegerField(default=garantias.models.generate_codigo_garantia, unique=True)),
                ('detalles_garantia', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('estados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garantias.estadosgarantia')),
                ('producto_con_garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product', verbose_name='Producto con garantía')),
                ('revision_garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garantias.revisiongarantiaproducto', verbose_name='revision garantia PRODUCTO')),
            ],
            options={
                'verbose_name': 'GarantíaProducto',
                'verbose_name_plural': 'Garantías Producto',
                'db_table': 'Garantia_Producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('codigo_garantia', models.PositiveIntegerField(default=garantias.models.generate_codigo_garantia, unique=True)),
                ('detalles_garantia', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('estados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garantias.estadosgarantia')),
                ('revision_garantia_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garantias.revisiongarantiaservicio', verbose_name='revision garantia SERVICIO')),
                ('servicio_con_garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garantias.serviciocongarantia', verbose_name='Servicio con garantía')),
            ],
            options={
                'verbose_name': 'Garantia_servicio',
                'verbose_name_plural': 'Garantías Servicio',
                'db_table': 'Garantia_servicio',
                'ordering': ['id'],
            },
        ),
    ]
